-- import table estacoes from "estacoes.csv";
-- import table obs from "observacoes.csv";
-- print table obs;


-- Comandos que funcionam
-- print table estacoes;
-- RENAME TABLE estacoes est;
-- discard table estacoes;
-- export table estacoes as "est.csv";

-- select * from est;
-- select Coordenadas from estacoes;
-- select Id from estacoes;
-- select Local from estacoes;
-- select Id, Local from estacoes;